name: japanese_vocab_quiz_en
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  rename: ^2.0.1
  get: 4.6.1
  get_storage: ^2.0.3
  firebase_core: ^1.16.0
  firebase_storage: ^10.2.15
  path_provider: ^2.0.9
  store_redirect: ^2.0.1
  expandable: ^5.0.1
  url_launcher: ^6.1.0
  flutter_email_sender: ^5.1.0
  url_strategy: ^0.2.0
  kana_kit: ^2.0.0
  google_mobile_ads: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#002868"
  image: assets/logo.png
  android: true

flutter_icons:
  android: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/help/
    - assets/tips/
    - assets/word_list/